### 반응 추가 (새 반응 or 기존 count +1)
POST http://localhost:3000/api/study/559ad647-6ec8-4476-8635-1a00de61ea87/reaction
Content-Type: application/json

{
  "emoji": "🔥"
}

### 특정 스터디의 모든 반응 조회
GET http://localhost:3000/api/study/559ad647-6ec8-4476-8635-1a00de61ea87/reaction

### 반응 감소 (새 반응 or 기존 count +1)
DELETE http://localhost:3000/study/559ad647-6ec8-4476-8635-1a00de61ea87/reaction
Content-Type: application/json

{
  "emoji": "🔥"
}